const DEFAULT_ACTION = 'UserDefault';
const FILTER_ACTION = 'UserFilter';
const DETAIL_ACTION = 'UserDetail';
const INSERT_ACTION = 'UserInsert';
const UPDATE_ACTION = 'UserUpdate';
const DELETE_ACTION = 'UserDelete';
const RESTORE_ACTION = 'UserRestore';
const PERMANENT_DELETE_ACTION = 'UserPermanentDelete';
const RESPONSE_ACTION = 'UserResponse';
const USERS_RESPONSE_ACTION = 'Users';
const USER_RESPONSE_ACTION = 'User';
const RESPONSE_DELETE_ACTION = 'UserResponseDelete';
const RESPONSE_RESTORE_ACTION = 'UserResponseRestore';
const RESPONSE_PERMANENT_DELETE_ACTION = 'UserResponsePermanentDelete';
const RESET_RESULT_ACTION = 'UserReset';
const RESET_STATUSCODE_ACTION = 'UserStatusCodeReset';
const USER_PROFILE_ACTION = 'UserProfile';
const PAGE_ACTION = 'UserPage';
const ROW_SELECT_ACTION = 'UserSelectRow';

export {
  DEFAULT_ACTION,
  FILTER_ACTION,
  DETAIL_ACTION,
  INSERT_ACTION,
  UPDATE_ACTION,
  DELETE_ACTION,
  RESTORE_ACTION,
  PERMANENT_DELETE_ACTION,
  RESPONSE_ACTION,
  USERS_RESPONSE_ACTION,
  USER_RESPONSE_ACTION,
  RESPONSE_DELETE_ACTION,
  RESPONSE_RESTORE_ACTION,
  RESPONSE_PERMANENT_DELETE_ACTION,
  RESET_RESULT_ACTION,
  RESET_STATUSCODE_ACTION,
  USER_PROFILE_ACTION,
  PAGE_ACTION,
  ROW_SELECT_ACTION,
};
