const DEFAULT_ACTION = 'FTPFileDefault';
const FILTER_ACTION = 'FTPFileFilter';
const DETAIL_ACTION = 'FTPFileDetail';
const RESEND_ACTION = 'FTPFileResend';
const DELETE_ACTION = 'FTPFileDelete';
const RESTORE_ACTION = 'FTPFileRestore';
const PERMANENT_DELETE_ACTION = 'FTPFilePermanentDelete';
const RESPONSE_ACTION = 'FTPFileResponse';
const FTPFILES_RESPONSE_ACTION = 'FTPFiles';
const FTPFILE_RESPONSE_ACTION = 'FTPFile';
const RESPONSE_DELETE_ACTION = 'FTPFileResponseDelete';
const RESPONSE_RESTORE_ACTION = 'FTPFileResponseRestore';
const RESPONSE_PERMANENT_DELETE_ACTION = 'FTPFileResponsePermanentDelete';
const RESET_RESULT_ACTION = 'FTPFileReset';
const RESET_STATUSCODE_ACTION = 'FTPFileStatusCodeReset';
const PAGE_ACTION = 'FTPFilePage';
const DOWNLOAD_ACTION = 'FTPFileFileDownload';
const RESPONSE_DOWNLOAD_ACTION = 'FTPFileResponseFileDownload';

export {
  DEFAULT_ACTION,
  FILTER_ACTION,
  DETAIL_ACTION,
  RESEND_ACTION,
  DELETE_ACTION,
  RESTORE_ACTION,
  PERMANENT_DELETE_ACTION,
  RESPONSE_ACTION,
  FTPFILES_RESPONSE_ACTION,
  FTPFILE_RESPONSE_ACTION,
  RESPONSE_DELETE_ACTION,
  RESPONSE_RESTORE_ACTION,
  RESPONSE_PERMANENT_DELETE_ACTION,
  RESET_RESULT_ACTION,
  RESET_STATUSCODE_ACTION,
  PAGE_ACTION,
  DOWNLOAD_ACTION,
  RESPONSE_DOWNLOAD_ACTION,
};
