const DEFAULT_ACTION = 'ScanDefault';
const FILTER_ACTION = 'ScanFilter';
const DETAIL_ACTION = 'ScanDetail';
const RESET_ACTION = 'ScanReset';
const SET_ACTION = 'ScanSet';
const SCANS_RESPONSE_ACTION = 'Scans';
const SCAN_RESPONSE_ACTION = 'Scan';
const RESET_STATUSCODE_ACTION = 'ScanStatusCodeReset';
const PAGE_ACTION = 'ScanPage';
const ROW_SELECT_ACTION = 'ScanSelectRow';
const RESPONSE_SCANCOUNT_ACTION = 'ScanCountResponse';
const RESPONSE_RESET_ACTION = 'ScanResetResponse';
const RESET_RESULT_ACTION = 'ResetResult';

export {
  DEFAULT_ACTION,
  FILTER_ACTION,
  DETAIL_ACTION,
  RESET_ACTION,
  SET_ACTION,
  SCANS_RESPONSE_ACTION,
  SCAN_RESPONSE_ACTION,
  RESET_STATUSCODE_ACTION,
  PAGE_ACTION,
  ROW_SELECT_ACTION,
  RESPONSE_SCANCOUNT_ACTION,
  RESPONSE_RESET_ACTION,
  RESET_RESULT_ACTION,
};
