const CHANGE_PASSWORD_ACTION = 'ChangePassword';
const CHANGE_PASSWORD_RESPONSE_ACTION = 'ChangePasswordResponse';
const CHANGE_PASSWORD_ERROR_ACTION = 'ChangePasswordError';
const RESET_CHANGE_PASSWORD_STORE_ACTION = 'ResetChangePasswordStore';

export {
  CHANGE_PASSWORD_ACTION,
  CHANGE_PASSWORD_RESPONSE_ACTION,
  CHANGE_PASSWORD_ERROR_ACTION,
  RESET_CHANGE_PASSWORD_STORE_ACTION,
};
