const DEFAULT_ACTION = 'InvoiceDefault';
const FILTER_ACTION = 'InvoiceFilter';
const DETAIL_ACTION = 'InvoiceDetail';
const REVIEW_ACTION = 'InvoiceReview';
const RESEND_ACTION = 'InvoiceResend';
const REVALIDATE_ACTION = 'InvoiceRevalidate';
const DELETE_ACTION = 'InvoiceDelete';
const RESTORE_ACTION = 'InvoiceRestore';
const PERMANENT_DELETE_ACTION = 'InvoicePermanentDelete';
const RESPONSE_ACTION = 'InvoiceResponse';
const INVOICES_RESPONSE_ACTION = 'Invoices';
const INVOICE_RESPONSE_ACTION = 'Invoice';
const RESPONSE_DELETE_ACTION = 'InvoiceResponseDelete';
const RESPONSE_RESTORE_ACTION = 'InvoiceResponseRestore';
const RESPONSE_PERMANENT_DELETE_ACTION = 'InvoiceResponsePermanentDelete';
const RESPONSE_CREATE_SELECT_LIST_ACTION = 'InvoiceResponseCreateSelectList';
const RESET_RESULT_ACTION = 'InvoiceReset';
const RESET_STATUSCODE_ACTION = 'InvoiceStatusCodeReset';
const PAGE_ACTION = 'InvoicePage';
const DOWNLOAD_ACTION = 'InvoiceFileDownload';
const RESPONSE_DOWNLOAD_ACTION = 'InvoiceResponseFileDownload';
export {
  DEFAULT_ACTION,
  FILTER_ACTION,
  DETAIL_ACTION,
  REVIEW_ACTION,
  RESEND_ACTION,
  REVALIDATE_ACTION,
  DELETE_ACTION,
  RESTORE_ACTION,
  PERMANENT_DELETE_ACTION,
  RESPONSE_ACTION,
  INVOICES_RESPONSE_ACTION,
  INVOICE_RESPONSE_ACTION,
  RESPONSE_DELETE_ACTION,
  RESPONSE_RESTORE_ACTION,
  RESPONSE_PERMANENT_DELETE_ACTION,
  RESPONSE_CREATE_SELECT_LIST_ACTION,
  RESET_RESULT_ACTION,
  RESET_STATUSCODE_ACTION,
  PAGE_ACTION,
  DOWNLOAD_ACTION,
  RESPONSE_DOWNLOAD_ACTION,
};
