const DEFAULT_ACTION = 'ShipmentLogDefault';
const FILTER_ACTION = 'ShipmentLogFilter';
const DETAIL_ACTION = 'ShipmentLogDetail';
const SHIPMENT_DETAIL_ACTION = 'ShipmentLogShipmentDetail';
const SHIPMENTLOGS_RESPONSE_ACTION = 'ShipmentLogs';
const SHIPMENTLOG_RESPONSE_ACTION = 'ShipmentLog';
const SHIPMENTLOG_SHIPMENT_RESPONSE_ACTION = 'ShipmentLogShipment';
const RESET_STATUSCODE_ACTION = 'ShipmentLogStatusCodeReset';
const PAGE_ACTION = 'ShipmentLogPage';
// request and response action
const RESPONSE_ACTION = 'Response';
const REQUEST_ACTION = 'Request';
const SHIPMENTLOG_DETAIL_RESPONSE_ACTION = 'ShipmentLogResponse';
const SHIPMENTLOG_DETAIL_REQUEST_ACTION = 'ShipmentLogRequest';
const SHIPMENTLOGS_RESPONSE_DETAIL_ACTION = 'ShipmentLogResponseDetail';
const SHIPMENTLOGS_REQUEST_DETAIL_ACTION = 'ShipmentLogRequestDetail';
const ROW_SELECT_ACTION = 'ShipmentLogSelectRow';

export {
  DEFAULT_ACTION,
  FILTER_ACTION,
  PAGE_ACTION,
  DETAIL_ACTION,
  SHIPMENT_DETAIL_ACTION,
  SHIPMENTLOGS_RESPONSE_ACTION,
  SHIPMENTLOG_RESPONSE_ACTION,
  SHIPMENTLOG_SHIPMENT_RESPONSE_ACTION,
  RESET_STATUSCODE_ACTION,
  RESPONSE_ACTION,
  REQUEST_ACTION,
  SHIPMENTLOG_DETAIL_RESPONSE_ACTION,
  SHIPMENTLOG_DETAIL_REQUEST_ACTION,
  SHIPMENTLOGS_RESPONSE_DETAIL_ACTION,
  SHIPMENTLOGS_REQUEST_DETAIL_ACTION,
  ROW_SELECT_ACTION,
};
