const DEFAULT_ACTION = 'EmailDefault';
const FILTER_ACTION = 'EmailFilter';
const DETAIL_ACTION = 'EmailDetail';
const DELETE_ACTION = 'EmailDelete';
const RESTORE_ACTION = 'EmailRestore';
const RESEND_ACTION = 'EmailResend';
const PERMANENT_DELETE_ACTION = 'EmailPermanentDelete';
const RESPONSE_ACTION = 'EmailResponse';
const EMAILS_RESPONSE_ACTION = 'Emails';
const EMAIL_RESPONSE_ACTION = 'Email';
const RESPONSE_DELETE_ACTION = 'EmailResponseDelete';
const RESPONSE_RESEND_ACTION = 'EmailResponseResend';
const RESPONSE_RESTORE_ACTION = 'EmailResponseRestore';
const RESPONSE_PERMANENT_DELETE_ACTION = 'EmailResponsePermanentDelete';
const RESET_RESULT_ACTION = 'EmailReset';
const RESET_STATUSCODE_ACTION = 'EmailStatusCodeReset';
const PAGE_ACTION = 'EmailPage';
const ROW_SELECT_ACTION = 'UserSelectRow';

export {
  DEFAULT_ACTION,
  FILTER_ACTION,
  DETAIL_ACTION,
  DELETE_ACTION,
  RESTORE_ACTION,
  RESEND_ACTION,
  PERMANENT_DELETE_ACTION,
  RESPONSE_ACTION,
  EMAILS_RESPONSE_ACTION,
  EMAIL_RESPONSE_ACTION,
  RESPONSE_DELETE_ACTION,
  RESPONSE_RESTORE_ACTION,
  RESPONSE_RESEND_ACTION,
  RESPONSE_PERMANENT_DELETE_ACTION,
  RESET_RESULT_ACTION,
  RESET_STATUSCODE_ACTION,
  PAGE_ACTION,
  ROW_SELECT_ACTION,
};
