const DAILY_BY_MONTH_ACTION = 'DailyByMonth';
const RESPONSE_DAILY_BY_MONTH_ACTION = 'DailyByMonthResponse';
const DAILY_BY_CURRENT_WEEK_ACTION = 'DailyByCurrentWeek';
const RESPONSE_DAILY_BY_CURRENT_WEEK_ACTION = 'DailyByCurrentWeekResponse';
const DAILY_BY_LAST_DAYS_ACTION = 'DailyByLastDays';
const RESPONSE_DAILY_BY_LAST_DAYS_ACTION = 'DailyByLastDaysResponse';
const MONTHLY_BY_YEAR_ACTION = 'MonthlyByYear';
const RESPONSE_MONTHLY_BY_YEAR_ACTION = 'MonthlyByYearResponse';
const SITE_MONTHLY_BY_YEAR_ACTION = 'SiteMonthlyByYear';
const RESPONSE_SITE_MONTHLY_BY_YEAR_ACTION = 'SiteMonthlyByYearResponse';
const SITE_MONTHLY_SUCCESS_BY_YEAR_ACTION = 'SiteMonthlySuccessByYear';
const RESPONSE_SITE_MONTHLY_SUCCESS_BY_YEAR_ACTION =
  'SiteMonthlySuccessByYearResponse';
const SITE_MONTHLY_FAILURE_BY_YEAR_ACTION = 'SiteMonthlyFailureByYear';
const RESPONSE_SITE_MONTHLY_FAILURE_BY_YEAR_ACTION =
  'SiteMonthlyFailureByYearResponse';
const RESET_STATUSCODE_ACTION = 'HomeStatusCodeReset';
const UPDATE_REPORT_LAYOUT = 'UpdateReportLayout';
const UPDATE_GRID_DRAGGABLE = 'UpdateGridDraggable';

export {
  DAILY_BY_MONTH_ACTION,
  RESPONSE_DAILY_BY_MONTH_ACTION,
  DAILY_BY_CURRENT_WEEK_ACTION,
  RESPONSE_DAILY_BY_CURRENT_WEEK_ACTION,
  DAILY_BY_LAST_DAYS_ACTION,
  RESPONSE_DAILY_BY_LAST_DAYS_ACTION,
  MONTHLY_BY_YEAR_ACTION,
  RESPONSE_MONTHLY_BY_YEAR_ACTION,
  SITE_MONTHLY_BY_YEAR_ACTION,
  RESPONSE_SITE_MONTHLY_BY_YEAR_ACTION,
  SITE_MONTHLY_SUCCESS_BY_YEAR_ACTION,
  RESPONSE_SITE_MONTHLY_SUCCESS_BY_YEAR_ACTION,
  SITE_MONTHLY_FAILURE_BY_YEAR_ACTION,
  RESPONSE_SITE_MONTHLY_FAILURE_BY_YEAR_ACTION,
  RESET_STATUSCODE_ACTION,
  UPDATE_REPORT_LAYOUT,
  UPDATE_GRID_DRAGGABLE,
};
